name: pre-commit

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]
    push:
        branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        python: python3.10
        system: true
        hooks: [black, flake8, commitlint, mypy]
        args: [--all-files, --verbose]
        additional_dependencies: ['@commitlint/config-conventional']
        exclude: 'mypy_report'
